services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: beetrack
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    healthcheck:
      interval: 5s
      retries: 5
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 5s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:9.8
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: demo@example.com
      PGADMIN_DEFAULT_PASSWORD: secret

      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      API_URL: http://localhost:8080
      APP_URL: http://localhost:5000
      DATABASE_URL: postgres://postgres:password@db:5432/beetrack?sslmode=disable
      IMAGE_STORAGE_PATH: /data/images
      PDF_STORAGE_PATH: /data/pdfs
      SMTP_FROM: noreply@beetrack.app
      SMTP_HOST: mailpit
      SMTP_PORT: "1025"
    ports:
      - "8080:8080"
    volumes:
      - images_data:/data/images
      - pdfs_data:/data/pdfs

volumes:
  postgres_data:
  images_data:
  pdfs_data:
