-- +goose Up
ALTER TABLE listings ADD COLUMN lat DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE listings ADD COLUMN lng DOUBLE PRECISION NOT NULL DEFAULT 0;

-- +goose Down
ALTER TABLE listings DROP COLUMN lat;
ALTER TABLE listings DROP COLUMN lng;
